---
abstract: 'Dancer plugin to cache response content (and anything else)'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Carp: 0
  Dancer::Test: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101590'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Cache
provides:
  Dancer::Plugin::Cache:
    file: lib/Dancer/Plugin/Cache.pm
    version: v0.2.0
requires:
  CHI: 0
  Dancer: 0
  Dancer::Plugin: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dancer-Plugin-Cache
  homepage: http://search.cpan.org/dist/Dancer-Plugin-Cache/
  repository: git://github.com/yanick/Dancer-Plugin-Cache.git
version: 0.2.0
x_authority: cpan:yanick
